name: Build Tauri iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: my-app # Указываем путь к проекту

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          brew install node
          npm install -g pnpm
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install tauri-cli

      - name: Install project dependencies
        run: pnpm install

      - name: Initialize Tauri iOS project
        run: pnpm tauri ios init

      - name: Build Tauri iOS app
        run: pnpm tauri ios build
