name: Build Tauri iOS App for AltStore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: my-app # Указываем путь к проекту

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          brew install node
          npm install -g pnpm
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install tauri-cli
          pnpm install  # Установка зависимостей

      - name: Setup Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Initialize Tauri iOS project
        run: pnpm tauri ios init

      - name: Build Tauri iOS app
        run: pnpm tauri ios build # Без флага --release

      - name: Find the .ipa file
        run: |
          echo "IPA_PATH=$(find src-tauri/gen/apple/target -name '*.ipa' | head -n 1)" >> $GITHUB_ENV

      - name: Upload .ipa file
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ${{ env.IPA_PATH }}
